export default {
    title:'DEVELOPER',
    name:'Jang Jun Young',
    ShowAboutImage:'true',
    headerImage:'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80',
    circleIcon1:'https://img.icons8.com/material-sharp/24/000000/filled-circle.png',
    introduction:[
        'My Name is me.',
        'Who dare dare dare?',
        'whats up, whats up, whats up, whats up, whats up, whats up, whats up,whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up, whats up,  ',
    ],

    aboutImage:'https://images.unsplash.com/photo-1573134005528-db6a82e51995?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=582&q=80',
    homeIcon:"https://mir-s3-cdn-cf.behance.net/project_modules/disp/7bf92c101264049.5f1ab4970ae14.png",
    projectIcon:"https://mir-s3-cdn-cf.behance.net/project_modules/disp/5697a7101264049.5f1ab40f60f8b.png",
    aboutIcon:"https://mir-s3-cdn-cf.behance.net/project_modules/disp/410427101264049.5f1ab4970b343.png",
    contactIcon:"https://mir-s3-cdn-cf.behance.net/project_modules/disp/f4d693101264049.5f1ab4970b75e.png",
    projects:[
        {
            id:1,
            title:'Web Backend',
            service:'Django Framework',
            imageSrc: "https://images.unsplash.com/photo-1558104631-0fa41a8f6c20?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60",
            url : "https://github.com/FreshTuna",
        },
        {
            id:2,
            title:'Web Backend',
            service:'Django Framework',
            imageSrc: "https://images.unsplash.com/photo-1558104631-0fa41a8f6c20?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60",
            url : "https://github.com/FreshTuna",
        },
        {
            id:3,
            title:'Web Backend',
            service:'Django Framework',
            imageSrc: "https://images.unsplash.com/photo-1558104631-0fa41a8f6c20?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60",
            url : "https://github.com/FreshTuna",
        },
        {
            id:4,
            title:'Web Backend',
            service:'Django Framework',
            imageSrc: "https://images.unsplash.com/photo-1558104631-0fa41a8f6c20?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60",
            url : "https://github.com/FreshTuna",
        },
        {
            id:5,
            title:'Web Backend',
            service:'Django Framework',
            imageSrc: "https://images.unsplash.com/photo-1558104631-0fa41a8f6c20?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60",
            url : "https://github.com/FreshTuna",
        },
        {
            id:6,
            title:'Web Backend',
            service:'Django Framework',
            imageSrc: "https://images.unsplash.com/photo-1558104631-0fa41a8f6c20?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60",
            url : "https://github.com/FreshTuna",
        },

    ],
    Email:'jun17114@gmail.com',
    Instagram: 'TunaJang',
    Site: 'https://github.com/FreshTuna',
}